-- An `engineer` role that can keep the logs and see nothing else.
--
-- WHY THIS IS A DATABASE CHANGE AND NOT A MENU CHANGE
--
-- `nav.js` / `canSee()` decide what appears in the sidebar. That is presentation
-- only. The Supabase anon key ships inside the JS bundle by design, so anybody
-- holding a valid login for a fleet can open a console and query any table their
-- RLS lets them reach — the UI is not in the path. Before this migration the
-- money tables had NO role-aware policy at all:
--
--     sales_landings / sales_rows        3 policies, 0 role-aware
--     su_settlements / su_settlement_lines  1 policy,  0 role-aware
--     quota_lines                        2 policies, 0 role-aware
--
-- They were scoped by fleet and nothing else, which was correct while every one
-- of the 13 users was a skipper. It stops being correct the moment a crewman
-- gets a login, and a phone in an engine room is an easier thing to lose than a
-- laptop in an office.
--
-- ALLOW-LIST, NOT DENY-LIST
--
-- The deny is generated by looping over every table in `public` and skipping an
-- explicit allow-list. That way a table added next year is denied to engineers
-- by default and someone has to think in order to open it up. A hand-written
-- deny-list would silently leak every new table — which is exactly the shape of
-- the bug this migration exists to fix.
--
-- Re-run this file after adding any table. It is idempotent.

-- ---------------------------------------------------------------------------
-- 1. The role
-- ---------------------------------------------------------------------------
-- NOTE: `alter type ... add value` cannot run in the same transaction that then
-- USES the new value, so this statement must be executed on its own, before the
-- rest of the file.

alter type public.user_role add value if not exists 'engineer';


-- ---------------------------------------------------------------------------
-- 2. The test
-- ---------------------------------------------------------------------------
-- `not is_engineer()` is the shape used throughout. It returns TRUE for a null
-- role rather than null, so every existing skipper/viewer/office/crew policy
-- behaves exactly as it did before this file ran. Only engineers are affected.

create or replace function public.is_engineer()
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $$
  select coalesce(public.current_user_role() = 'engineer'::public.user_role, false)
$$;

comment on function public.is_engineer() is
  'True when the calling user is an engineer. Used as `not is_engineer()` in '
  'restrictive policies, so a null role reads as "not an engineer" and existing '
  'roles are unaffected.';

grant execute on function public.is_engineer() to authenticated;


-- ---------------------------------------------------------------------------
-- 3. Deny everything except the allow-list
-- ---------------------------------------------------------------------------
-- Restrictive policies AND together with each other and with the permissive
-- ones, so a single restrictive policy per table is enough to close it — the
-- existing policies do not need touching, and skipper behaviour cannot change.

do $$
declare
  t text;
  allowed text[] := array[
    -- writes: the logs an engineer actually keeps
    'engine_logs', 'vessel_fuel_log', 'garbage_log', 'fuel_suppliers',
    -- reads: the papers he needs, and the rows the app shell needs to boot
    'vessel_certificates', 'vessel_details', 'fleets', 'settings',
    'app_users', 'crew'
  ];
begin
  for t in
    select c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind = 'r'
      and c.relrowsecurity                      -- only tables with RLS on
      and not (c.relname = any(allowed))
  loop
    execute format('drop policy if exists engineer_no_access on public.%I', t);
    execute format(
      'create policy engineer_no_access on public.%I as restrictive for all '
      'to authenticated using (not public.is_engineer()) '
      'with check (not public.is_engineer())', t);
  end loop;
end $$;


-- ---------------------------------------------------------------------------
-- 4. Read-only for the papers and the shell
-- ---------------------------------------------------------------------------
-- These are readable but must not be writable. `crew` and `app_users` already
-- scope an ordinary user to their OWN row (crew_read_all checks
-- `id = current_user_crew_id()`, app_users_self_read checks `id = auth.uid()`),
-- so an engineer sees himself and no one else. This only blocks writes.

do $$
declare
  t text;
  readonly text[] := array[
    'vessel_certificates', 'vessel_details', 'fleets', 'settings',
    'app_users', 'crew'
  ];
begin
  foreach t in array readonly loop
    execute format('drop policy if exists engineer_read_only_ins on public.%I', t);
    execute format('drop policy if exists engineer_read_only_upd on public.%I', t);
    execute format('drop policy if exists engineer_read_only_del on public.%I', t);

    execute format(
      'create policy engineer_read_only_ins on public.%I as restrictive '
      'for insert to authenticated with check (not public.is_engineer())', t);
    execute format(
      'create policy engineer_read_only_upd on public.%I as restrictive '
      'for update to authenticated using (not public.is_engineer()) '
      'with check (not public.is_engineer())', t);
    execute format(
      'create policy engineer_read_only_del on public.%I as restrictive '
      'for delete to authenticated using (not public.is_engineer())', t);
  end loop;
end $$;


-- ---------------------------------------------------------------------------
-- 5. Grant the engineer what he does need
-- ---------------------------------------------------------------------------
-- Every one of these tables reads `role in (skipper, viewer)` and writes
-- `role = skipper`, so an engineer is currently denied by all four. Rather than
-- editing those policies — and risking a skipper's access on a typo — add a
-- separate permissive policy per table. The restrictive fleet_isolation policy
-- still applies on top, so an engineer is confined to his own fleet.

do $$
declare
  t text;
begin
  foreach t in array array['engine_logs', 'vessel_fuel_log', 'garbage_log', 'fuel_suppliers'] loop
    execute format('drop policy if exists engineer_keeps_log on public.%I', t);
    execute format(
      'create policy engineer_keeps_log on public.%I for all to authenticated '
      'using (public.is_engineer()) with check (public.is_engineer())', t);
  end loop;
end $$;

-- Vessel certificates: read, never write. He needs to see when the liferaft
-- service or the fire-extinguisher certificate runs out; renewing them is the
-- skipper's job. Section 4 already blocks his writes.
drop policy if exists engineer_reads_certs on public.vessel_certificates;
create policy engineer_reads_certs on public.vessel_certificates
  for select to authenticated using (public.is_engineer());

-- vessel_details is skipper-only today (`vessel_details_skipper` is its only
-- permissive policy), and EngineLogs.jsx reads it — without this the engine log
-- page loads blank. Deliberately scoped to engineers rather than opened to all
-- fleet members, so no existing role's access changes in this migration.
drop policy if exists engineer_reads_vessel on public.vessel_details;
create policy engineer_reads_vessel on public.vessel_details
  for select to authenticated using (public.is_engineer());


-- ---------------------------------------------------------------------------
-- 6. Storage
-- ---------------------------------------------------------------------------
-- None of the four engineer pages upload or fetch a file today (all 15 vessel
-- certificates carry a null file_path — the images are still only in Aegir), so
-- an engineer needs no bucket at all. Deny the lot; revisit when cert files get
-- a bucket of their own.
--
-- Written as `storage.objects.name` would be if this policy referenced the path
-- at all — see the su_docs_* shadowing bug in CLAUDE.md. It does not, so there
-- is nothing here for an inner relation to capture.

drop policy if exists engineer_no_storage on storage.objects;
create policy engineer_no_storage on storage.objects as restrictive
  for all to authenticated
  using (not public.is_engineer())
  with check (not public.is_engineer());
