-- `engineer` becomes `officer`: a working ticket for anyone aboard who keeps
-- records — engineers, mates — but who has no business in the money.
--
-- This supersedes `engineer_role.sql`. Same allow-list machinery, wider list.
-- Re-run this file, NOT that one, after adding any table.
--
-- WHAT CHANGED AND WHY
--
-- The engineer role was built for one man and one job: the logs. Widening it to
-- mates means it also has to carry the crew paperwork they actually do — adding
-- a man to the system, filing his tickets, and producing a crew list. That is
-- the same paperwork a skipper does, so the role is now materially more
-- powerful and the boundary matters more, not less.
--
-- What it still CANNOT touch is the money: sales, settlements, quota, contracts,
-- payments and bonuses are all denied, and that is the whole point of the role
-- existing rather than just handing out a skipper login.
--
-- `is_officer()` accepts the legacy 'engineer' value as well as 'officer', so
-- an unmigrated login keeps working. The two live engineer logins are migrated
-- at the end of this file.

-- 1. -------------------------------------------------------------------------
-- alter type ... add value must already have been run in its own transaction:
--   alter type public.user_role add value if not exists 'officer';

create or replace function public.is_officer()
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select coalesce(public.current_user_role() in ('officer','engineer'), false)
$$;

comment on function public.is_officer() is
  'True for an officer (engineer, mate) login. Accepts the legacy engineer '
  'value too. Used as `not is_officer()` in restrictive policies so a null role '
  'reads as "not an officer" and no existing role is affected.';

grant execute on function public.is_officer() to authenticated;


-- 2. Deny everything outside the allow-list --------------------------------
-- Generated by a loop over every table, so a table added next year is denied
-- by default and somebody has to think in order to open it up. A hand-written
-- deny-list would silently leak every new table.
do $$
declare
  t text;
  allowed text[] := array[
    -- writes: the logs and the maintenance record
    'engine_logs', 'vessel_fuel_log', 'garbage_log', 'fuel_suppliers',
    'maintenance_tasks', 'maintenance_events',
    -- writes: crew paperwork. A mate adds a man, files his tickets and makes
    -- the crew list — none of which touches what anyone is paid.
    'crew', 'crew_certificates', 'crew_lists', 'crew_list_members',
    -- reads: the papers he needs, and the rows the app shell needs to boot
    'vessel_certificates', 'vessel_details', 'fleets', 'settings', 'app_users'
  ];
begin
  for t in
    select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
      and not (c.relname = any(allowed))
  loop
    execute format('drop policy if exists engineer_no_access on public.%I', t);
    execute format('drop policy if exists officer_no_access on public.%I', t);
    execute format(
      'create policy officer_no_access on public.%I as restrictive for all '
      'to authenticated using (not public.is_officer()) '
      'with check (not public.is_officer())', t);
  end loop;
end $$;


-- 2b. Clean up tables that have just JOINED the allow-list -----------------
-- The loop above only touches tables OUTSIDE the list, so it cannot clear the
-- denial a table was given the last time it was outside. crew_certificates,
-- crew_lists and crew_list_members were all denied under engineer_role.sql and
-- kept their `engineer_no_access` policy — officers would have been shut out of
-- crew certs and crew lists with everything else looking correct.
--
-- Caught because section 7 drops the old helper WITHOUT cascade: Postgres
-- refused, and named the three policies still depending on it. Keep that DROP
-- plain for exactly this reason.
do $$
declare
  t text;
  allowed text[] := array[
    'engine_logs','vessel_fuel_log','garbage_log','fuel_suppliers',
    'maintenance_tasks','maintenance_events',
    'crew','crew_certificates','crew_lists','crew_list_members',
    'vessel_certificates','vessel_details','fleets','settings','app_users'
  ];
begin
  foreach t in array allowed loop
    execute format('drop policy if exists engineer_no_access on public.%I', t);
    execute format('drop policy if exists officer_no_access on public.%I', t);
  end loop;
end $$;


-- 3. Read-only for the papers and the shell --------------------------------
-- `crew` is NO LONGER in this list — an officer adds and edits crew. The rest
-- he may read and must not change.
do $$
declare
  t text;
begin
  foreach t in array array['vessel_certificates','vessel_details','fleets','settings','app_users'] loop
    execute format('drop policy if exists engineer_read_only_ins on public.%I', t);
    execute format('drop policy if exists engineer_read_only_upd on public.%I', t);
    execute format('drop policy if exists engineer_read_only_del on public.%I', t);
    execute format('drop policy if exists officer_read_only_ins on public.%I', t);
    execute format('drop policy if exists officer_read_only_upd on public.%I', t);
    execute format('drop policy if exists officer_read_only_del on public.%I', t);

    execute format('create policy officer_read_only_ins on public.%I as restrictive '
      'for insert to authenticated with check (not public.is_officer())', t);
    execute format('create policy officer_read_only_upd on public.%I as restrictive '
      'for update to authenticated using (not public.is_officer()) '
      'with check (not public.is_officer())', t);
    execute format('create policy officer_read_only_del on public.%I as restrictive '
      'for delete to authenticated using (not public.is_officer())', t);
  end loop;
end $$;


-- 4. Grant what he does need ------------------------------------------------
-- Separate permissive policies rather than editing the existing ones, so a typo
-- here cannot cost a skipper his access. The restrictive fleet_isolation policy
-- still applies on top, confining him to his own boat.
do $$
declare
  t text;
begin
  foreach t in array array[
    'engine_logs','vessel_fuel_log','garbage_log','fuel_suppliers',
    'maintenance_tasks','maintenance_events',
    'crew','crew_certificates','crew_lists','crew_list_members'
  ] loop
    execute format('drop policy if exists engineer_keeps_log on public.%I', t);
    execute format('drop policy if exists officer_works on public.%I', t);
    execute format(
      'create policy officer_works on public.%I for all to authenticated '
      'using (public.is_officer()) with check (public.is_officer())', t);
  end loop;
end $$;

-- Vessel certificates: read, never write. He needs to see when the liferaft
-- service runs out; renewing it is the skipper's job. Section 3 blocks writes.
drop policy if exists engineer_reads_certs on public.vessel_certificates;
drop policy if exists officer_reads_certs on public.vessel_certificates;
create policy officer_reads_certs on public.vessel_certificates
  for select to authenticated using (public.is_officer());

-- vessel_details is skipper-only for reading and EngineLogs/CrewList both read
-- it — without this the engine-log page and the crew-list header come up blank.
drop policy if exists engineer_reads_vessel on public.vessel_details;
drop policy if exists officer_reads_vessel on public.vessel_details;
create policy officer_reads_vessel on public.vessel_details
  for select to authenticated using (public.is_officer());


-- 5. Storage ----------------------------------------------------------------
-- Filing a man's tickets means uploading files, so the blanket storage denial
-- has to open by exactly one bucket. Everything else — settlement documents,
-- fleet photos, the Square Up buckets — stays shut.
--
-- `storage.objects.name` is qualified deliberately: the su_docs_* bug came from
-- a bare `name` inside a subquery binding to su_boats.name instead. There is no
-- subquery here, but the habit is the fix.
drop policy if exists engineer_no_storage on storage.objects;
drop policy if exists officer_storage_scope on storage.objects;
create policy officer_storage_scope on storage.objects as restrictive
  for all to authenticated
  using (not public.is_officer() or bucket_id in ('crew-certs','vessel-certs'))
  with check (not public.is_officer() or bucket_id = 'crew-certs');

-- The existing crew_certs_insert/update/delete policies require a skipper, so
-- an officer needs his own. Same fleet-folder check as theirs.
drop policy if exists officer_crew_certs_write on storage.objects;
create policy officer_crew_certs_write on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'crew-certs'
    and (storage.foldername(storage.objects.name))[1] = current_fleet_id()::text
    and public.is_officer()
  );

drop policy if exists officer_crew_certs_update on storage.objects;
create policy officer_crew_certs_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'crew-certs'
    and (storage.foldername(storage.objects.name))[1] = current_fleet_id()::text
    and public.is_officer()
  );

drop policy if exists officer_crew_certs_delete on storage.objects;
create policy officer_crew_certs_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'crew-certs'
    and (storage.foldername(storage.objects.name))[1] = current_fleet_id()::text
    and public.is_officer()
  );

-- Reading a vessel-cert file: the existing vessel_certs_read is skipper/viewer.
drop policy if exists officer_vessel_certs_read on storage.objects;
create policy officer_vessel_certs_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'vessel-certs'
    and (storage.foldername(storage.objects.name))[1] = current_fleet_id()::text
    and public.is_officer()
  );


-- 6. Migrate the two live engineer logins -----------------------------------
update public.app_users set role = 'officer' where role = 'engineer';


-- 7. Retire the old helper --------------------------------------------------
-- Plain DROP, never CASCADE: if a policy somewhere still references it, this
-- fails and tells us, rather than silently taking that policy with it.
drop function if exists public.is_engineer();


-- ============================================================
-- VERIFY
-- ============================================================
-- Nothing outside the allow-list left open:
--   select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
--    where n.nspname='public' and c.relkind='r' and c.relrowsecurity
--      and not exists (select 1 from pg_policies p where p.schemaname='public'
--                        and p.tablename=c.relname and p.policyname='officer_no_access');
