-- Fill the vessel_id the app failed to stamp while VesselProvider was not in
-- the tree. Sep 2026.
--
-- WHY THE ROWS ARE THERE. `VesselProvider` was imported into `App.jsx` and
-- never rendered, so every `useCurrentVessel()` read the module default and
-- `current` was permanently null. Pages that stamp the boat on insert stamped
-- nothing, and pages that scope by boat scoped nothing — which is exactly why
-- nobody noticed: reading behaved as "show everything", so the only visible
-- symptom was the certification pages saying "No vessel on file".
--
-- Mounting the provider turns the scoping ON, and every one of these rows would
-- then vanish from the page that wrote it. **So the repair is part of the fix,
-- not a tidy-up after it** — shipping the provider without this would take an
-- engine log, two crew lists, two vessel certificates and a stores list off
-- Audacious's pages.
--
--     vessel_departures   864 of 1,577    AUDACIOUS
--     sales_landings       10 of 357      AUDACIOUS + BOY JOHN/ROSEBLOOM
--     engine_logs           3             AUDACIOUS
--     crew_lists            2             AUDACIOUS
--     garbage_log           2             AUDACIOUS
--     landings              2             AUDACIOUS
--     vessel_certificates   2             AUDACIOUS
--     stores_lists          1             AUDACIOUS
--     vessel_fuel_log       1             AUDACIOUS
--     quota_trips           1             AUDACIOUS
--
-- NOTHING IS GUESSED, and the two rules are the ones stage 2 already used.
--
-- 1. A SALES NOTE NAMES ITS OWN BOAT. `sales_landings.vessel` carries the
--    label, so those ten are a real join and not an inference — which matters
--    because four of them are BOY JOHN and four ROSEBLOOM, a pair fleet where
--    "the only boat" is not an answer. Done FIRST, so the pair fleet is settled
--    before the single-vessel rule runs at all.
--
-- 2. A FLEET WITH EXACTLY ONE BOAT HAS ONLY ONE POSSIBLE ANSWER. That is not a
--    guess either. Any fleet with two is left alone.
--
-- Generated by a loop over every table carrying `vessel_id`, so a table added
-- later is covered without editing a list — same reasoning as the role files'
-- deny-lists, and the same reason a hand-written list would rot.
--
-- LEFT NULL DELIBERATELY, and both are correct:
--   HANSTHOLM's 4 rota_trips  — that fleet has no `vessels` row at all, so
--     there is no boat to point at. Inventing one is worse than an honest null.
--   TEST FLEET's 1 quota_manual_stocks — a pair, and the row says nothing about
--     which half it belongs to.
--
-- Only ever fills a NULL. It cannot move a row already assigned, so it is safe
-- to run again.

-- 1. The notes that name their own boat -------------------------------------
update public.sales_landings l
set vessel_id = v.id
from public.vessels v
where l.vessel_id is null
  and v.fleet_id = l.fleet_id
  and upper(v.label) = upper(l.vessel);

-- 2. Single-vessel fleets, every remaining table -----------------------------
do $$
declare
  t record;
  filled int;
  total int := 0;
begin
  for t in
    select c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attname = 'vessel_id'
      and a.attnum > 0 and not a.attisdropped
    join pg_attribute f on f.attrelid = c.oid and f.attname = 'fleet_id'
      and f.attnum > 0 and not f.attisdropped
    where n.nspname = 'public' and c.relkind = 'r'
    order by c.relname
  loop
    execute format($q$
      update public.%I x
      set vessel_id = one.id
      from (
        -- min(uuid) does not exist, and there is nothing to aggregate anyway:
        -- the subquery already says this fleet has exactly one boat.
        select v.fleet_id, v.id
        from public.vessels v
        where coalesce(v.active, true)
          and 1 = (select count(*) from public.vessels w
                    where w.fleet_id = v.fleet_id and coalesce(w.active, true))
      ) one
      where x.vessel_id is null and x.fleet_id = one.fleet_id
    $q$, t.relname);
    get diagnostics filled = row_count;
    total := total + filled;
    if filled > 0 then
      raise notice '% : % rows', t.relname, filled;
    end if;
  end loop;
  raise notice 'total filled: %', total;
end $$;
